// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIsjIC0D2nNE-LrFApL5oc4u9ydhk53B0',
    appId: '1:1092416280147:web:0159f2eab643a93ace58a6',
    messagingSenderId: '1092416280147',
    projectId: 'fir-storage-8d7a3',
    authDomain: 'fir-storage-8d7a3.firebaseapp.com',
    storageBucket: 'fir-storage-8d7a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8gVnt3nNIw8EXk_OV1Wavs8RyUrym-9M',
    appId: '1:1092416280147:android:da6af75a17f43fbace58a6',
    messagingSenderId: '1092416280147',
    projectId: 'fir-storage-8d7a3',
    storageBucket: 'fir-storage-8d7a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNEsWhyrZqhovsC9BjDXyjHmFXZ0_Mjac',
    appId: '1:1092416280147:ios:2451c80a387646b7ce58a6',
    messagingSenderId: '1092416280147',
    projectId: 'fir-storage-8d7a3',
    storageBucket: 'fir-storage-8d7a3.appspot.com',
    iosClientId: '1092416280147-n8l421hp8ovd4l1jkdctv38roidg4aa1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseStorage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNEsWhyrZqhovsC9BjDXyjHmFXZ0_Mjac',
    appId: '1:1092416280147:ios:e1d47ede2ccb7f73ce58a6',
    messagingSenderId: '1092416280147',
    projectId: 'fir-storage-8d7a3',
    storageBucket: 'fir-storage-8d7a3.appspot.com',
    iosClientId: '1092416280147-70clcqqjna8mbj684sq71jjdmr5l657g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseStorage.RunnerTests',
  );
}
